/*
 *	This file is generated by script PS_Exporter
 *	Please Do Not Modify it manually
 *	Author : dotboy
 */
 
 
 @interface <ifName>(<cgName>)
 - (void)setupUI:(UIView *)parentView;
 @end
 
 @implementation <ifName>(<cgName>)
 - (void)setupUI:(UIView *)parentView
 {
 
